name: Build Docker Image and Push to ACR
#aaaa
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout main'
      uses: actions/checkout@v2

    - name: 'Sign in to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build & Push to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: helloAppContainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t helloAppContainer.azurecr.io/dockerhelloapp:${{ github.sha }}
        docker push helloAppContainer.azurecr.io/dockerhelloapp:${{ github.sha }}

    - name: 'Deploy from ACR to App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'helloDockerEylul'  # Your Azure App Service name
        images: 'helloAppContainer.azurecr.io/dockerhelloapp:${{ github.sha }}'
        

    - run: |
        az logout
